version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@db:3306/mydatabase"
    ports:
      - "8000:8000"

volumes:
  mysql_data:
